import { z } from 'zod'
import { STATION_LAYOUT } from './stationLayout'

const MediaPointSchema = z.object({
  id: z.string(),
  number: z.number().int().min(1),
  name: z.string(),
  location: z.string(),
  type: z.enum(['digital', 'print']),
  surface: z.string(),
  width: z.number().positive(),
  height: z.number().positive(),
  position: z.tuple([z.number(), z.number(), z.number()]),
  rotation: z.tuple([z.number(), z.number(), z.number()]),
})
export type MediaPoint = z.infer<typeof MediaPointSchema>

const { frontZ, backZ } = STATION_LAYOUT.islands
export const MEDIA_POINTS: MediaPoint[] = z.array(MediaPointSchema).parse([
  {
    id: 'mp-01',
    number: 1,
    name: 'Pump Topper 1',
    location: 'Isola anteriore',
    type: 'digital',
    surface: 'LED screen',
    width: 1.6,
    height: 0.55,
    position: [4, 3.05, frontZ + 0.72],
    rotation: [0, 0, 0],
  },
  {
    id: 'mp-02',
    number: 2,
    name: 'Pump Side 1',
    location: 'Isola anteriore',
    type: 'print',
    surface: 'Pannello laterale',
    width: 0.8,
    height: 1.15,
    position: [7.8, 1.25, frontZ + 0.72],
    rotation: [0, 0, 0],
  },
  {
    id: 'mp-03',
    number: 3,
    name: 'Shop Fascia',
    location: 'Shop',
    type: 'digital',
    surface: 'LED screen',
    width: 3.4,
    height: 0.7,
    position: [13, 4.2, -5.95],
    rotation: [0, 0, 0],
  },
  {
    id: 'mp-04',
    number: 4,
    name: 'Column Wrap',
    location: 'Pensilina',
    type: 'print',
    surface: 'Pannello colonna',
    width: 0.75,
    height: 1.5,
    position: [7, 2.2, backZ + 0.45],
    rotation: [0, 0, 0],
  },
  {
    id: 'mp-05',
    number: 5,
    name: 'Pump Topper 2',
    location: 'Isola posteriore',
    type: 'digital',
    surface: 'LED screen',
    width: 1.6,
    height: 0.55,
    position: [-4, 3.05, backZ + 0.72],
    rotation: [0, 0, 0],
  },
  {
    id: 'mp-06',
    number: 6,
    name: 'Shop Poster',
    location: 'Shop',
    type: 'print',
    surface: 'Vetrina',
    width: 1.1,
    height: 1.7,
    position: [19, 2.1, -5.94],
    rotation: [0, 0, 0],
  },
  {
    id: 'mp-07',
    number: 7,
    name: 'Totem Lower Panel',
    location: 'Ingresso',
    type: 'print',
    surface: 'Totem',
    width: 2.1,
    height: 1.45,
    position: [-22, 2.15, -8.34],
    rotation: [0, 0, 0],
  },
  {
    id: 'mp-08',
    number: 8,
    name: 'Forecourt Poster',
    location: 'Ingresso piazzale',
    type: 'print',
    surface: 'Freestanding',
    width: 1.5,
    height: 1.8,
    position: [-13, 1.45, 9],
    rotation: [0, 0, 0],
  },
  {
    id: 'mp-09',
    number: 9,
    name: 'Flag',
    location: 'Ingresso piazzale',
    type: 'print',
    surface: 'Bandiera',
    width: 1.15,
    height: 2.7,
    position: [-20, 2.3, 8],
    rotation: [0, 0, 0],
  },
  {
    id: 'mp-10',
    number: 10,
    name: 'Shop Header',
    location: 'Shop',
    type: 'digital',
    surface: 'LED screen',
    width: 2.2,
    height: 0.65,
    position: [9.4, 4.2, -5.94],
    rotation: [0, 0, 0],
  },
])
